test_app/config/routes.rb
Rails.application.routes.draw do
  resources :groceries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'groceries#index'
end

test_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

test_app/app/models/grocery.rb
class Grocery < ApplicationRecord
end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

test_app/app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
  before_action :set_grocery, only: %i[ show edit update destroy ]

  # GET /groceries or /groceries.json
  def index
    @groceries = Grocery.all
  end

  # GET /groceries/1 or /groceries/1.json
  def show
  end

  # GET /groceries/new
  def new
    @grocery = Grocery.new
  end

  # GET /groceries/1/edit
  def edit
  end

  # POST /groceries or /groceries.json
  def create
    @grocery = Grocery.new(grocery_params)

    respond_to do |format|
      if @grocery.save
        format.html { redirect_to grocery_url(@grocery), notice: "Grocery was successfully created." }
        format.json { render :show, status: :created, location: @grocery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grocery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groceries/1 or /groceries/1.json
  def update
    respond_to do |format|
      if @grocery.update(grocery_params)
        format.html { redirect_to grocery_url(@grocery), notice: "Grocery was successfully updated." }
        format.json { render :show, status: :ok, location: @grocery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grocery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groceries/1 or /groceries/1.json
  def destroy
    @grocery.destroy

    respond_to do |format|
      format.html { redirect_to groceries_url, notice: "Grocery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grocery
      @grocery = Grocery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grocery_params
      params.require(:grocery).permit(:name, :facts)
    end
end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_app/app/helpers/groceries_helper.rb
module GroceriesHelper
end

test_app/app/views/groceries/_form.html.erb
<%= form_with(model: grocery) do |form| %>
  <% if grocery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(grocery.errors.count, "error") %> prohibited this grocery from being saved:</h2>

      <ul>
        <% grocery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :facts, style: "display: block" %>
    <%= form.text_area :facts %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

test_app/app/views/groceries/_grocery.html.erb
<div id="<%= dom_id grocery %>">
  <p>
    <strong>Name:</strong>
    <%= grocery.name %>
  </p>

  <p>
    <strong>Facts:</strong>
    <%= grocery.facts %>
  </p>

</div>

test_app/app/views/groceries/edit.html.erb
<h1>Editing grocery</h1>

<%= render "form", grocery: @grocery %>

<br>

<div>
  <%= link_to "Show this grocery", @grocery %> |
  <%= link_to "Back to groceries", groceries_path %>
</div>

test_app/app/views/groceries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Groceries</h1>

<div id="groceries">
  <% @groceries.each do |grocery| %>
    <%= render grocery %>
    <p>
      <%= link_to "Show this grocery", grocery %>
    </p>
  <% end %>
</div>



<%= result = `python lib/assets/python_test/test.py` %>
<%= link_to "New grocery", new_grocery_path %>

test_app/app/views/groceries/new.html.erb
<h1>New grocery</h1>

<%= render "form", grocery: @grocery %>

<br>

<div>
  <%= link_to "Back to groceries", groceries_path %>
</div>

test_app/app/views/groceries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @grocery %>

<div>
  <%= link_to "Edit this grocery", edit_grocery_path(@grocery) %> |
  <%= link_to "Back to groceries", groceries_path %>

  <%= button_to "Destroy this grocery", @grocery, method: :delete %>
</div>

test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>